import "@/styles/globals.css";
//import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({

  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

//import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


type Props = {
  children: React.ReactNode
}
const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.className} bg-gray-100 text-zinc-900 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export default RootLayout
